name: org.shelden93.xhtml

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - 'develop'
    paths:
      - plugins/org.shelden93.xhtml/**
  push:
    branches:
      - 'develop'
    paths:
      - plugins/org.shelden93.xhtml/**

jobs:
  test:
    name: XSpec Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Initialize Tools
        run: ./mvnw package -pl tools
      - name: Run XSpec Tests
        run: ./mvnw test -pl plugins/org.shelden93.xhtml
      - name: XSpec Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: XSpec JUnit Test Reports
          path: '**/target/xspec/**/*-junit.xml'
          reporter: jest-junit
  build:
    name: Deploy to GitHub Packages
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish Plugin
        run: ./mvnw deploy -pl plugins/org.shelden93.xhtml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
